services:
  postgres:
    container_name: postgres_db
    working_dir: /postgres
    build:
      context: .
      dockerfile: database.Dockerfile
      args:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app_network
    image: postgres_db:test

  fastapi:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: fastapi.Dockerfile
      args:
        APP_PORT: ${APP_PORT}
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    networks:
      - app_network
    image: fastapi:test
    command: ["sh", "-c", "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port ${APP_PORT}"]

volumes:
  db_data:
    name: "db_postgres_data"
    external: true

networks:
  app_network:
    driver: bridge