"""Update Users

Revision ID: 8df03a3027f1
Revises: f29b1c6e13ce
Create Date: 2024-09-10 18:31:07.140801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df03a3027f1'
down_revision: Union[str, None] = 'f29b1c6e13ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram_number')
    # ### end Alembic commands ###
